name: Fetch Crypto Prices and Create Release

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch: # Allow manual trigger of the workflow

jobs:
  fetch-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies with pnpm
      run: |
        corepack enable
        pnpm install

    - name: Run script to fetch prices
      env:
        CMC_API_KEY: ${{ secrets.CMC_API_KEY }}
      run: node src/index.js

    - name: Commit and push crypto_prices.json
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Update crypto prices for $(date -u '+%Y-%m-%d %H:%M:%S')"
        file_pattern: prices.json

    - name: Create and push initial tag
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        TAG_NAME=$(date -u '+%Y.%m.%d.%H')
        git tag $TAG_NAME
        git push origin $TAG_NAME

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: "$(date -u '+%Y.%m.%d.%H')"
        release_name: "Crypto Prices - $(date -u '+%Y.%m.%d %H:%M')"
        draft: false
        prerelease: false

    - name: Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./prices.json
        asset_name: prices.json
        asset_content_type: application/json
