name: Fetch Crypto Prices and Create Release

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  fetch-and-release:
    runs-on: ubuntu-latest
    env:
      TZ: America/New_York
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies with pnpm
      run: |
        corepack enable
        pnpm install --frozen-lockfile

    - name: Run script to fetch prices
      env:
        CMC_API_KEY: ${{ secrets.CMC_API_KEY }}
      run: node src/index.js

    - name: Commit and push crypto_prices.json
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Updated Pricing"
        file_pattern: dist/prices.json

    - name: Create and push initial tag
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        TAG_NAME=v$(date -u '+%Y.%m.%d%H')
        git tag $TAG_NAME
        git push origin $TAG_NAME

    - name: Create GitHub release
      uses: softprops/action-gh-release@v2
      with:
        files: dist/prices.json
        tag_name: v$(date -u '+%Y.%m.%d%H')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}